### ISSUE TITLE
Word motions include the adjacent word boundary char when it shouldn't

### ISSUE THREAD

**Issue by aaronNGi** [aligrudi/neatvi#10]
Given the text `foo bar baz` and the cursor being on the 'b' of "bar", pressing <kbd>c</kbd><kbd>w</kbd> and entering qux<kbd>Esc</kbd> leaves the text as `foo quxbaz`. That behaviour makes sense for <kbd>d</kbd><kbd>w</kbd> but is awkward for <kbd>c</kbd><kbd>w</kbd>.

When changing or deleting the last word of a line, the newline gets swallowed resulting in joining with the next line.

**Comment by aligrudi** [comment]
Aaron G <notifications@github.com> wrote:
> Given the text `foo bar baz` and the cursor being on the 'b' of
> "bar", pressing <kbd>c</kbd><kbd>w</kbd> and entering
> qux<kbd>Esc</kbd> leaves the text as `foo quxbaz`. That behaviour
> makes sense for <kbd>d</kbd><kbd>w</kbd> but is awkward for
> <kbd>c</kbd><kbd>w</kbd>.

In most vi implementation, cw acts like ce.  The reason for this
inconsistency is backward incompatibility.  The behaviour of cw
always surprised me and I decided not to put it in Neatvi.

> When changing or deleting the last word of a line, the newline gets
> swallowed resulting in joining with the next line.

Solving this does not seem very clean; vc_motion and mot.c need
to be modified for that.  I shall investigate it later.

Thanks,
Ali

**Comment by aaronNGi** [comment]
I kinda got used to it now. Muscle memory makes it easy to hate on something you are not used to. Being able to delete the last word of a line which includes the newline could be considered an advantage even.
