### ISSUE TITLE
Uppercasing a word at the end of the line does not trigger a redraw

### ISSUE THREAD

**Issue by aaronNGi** [aligrudi/neatvi#11]
Using <kbd>g</kbd><kbd>U</kbd><kbd>w</kbd> on the last word of a line, does not show the change until <kbd>Ctrl</kbd>+<kbd>l</kbd> is pressed. It also puts the cursor onto the first char of the next line (probably related to #10).

**Comment by aligrudi** [comment]
Aaron G <notifications@github.com> wrote:
> Using <kbd>g</kbd><kbd>U</kbd><kbd>w</kbd> on the last word of a
> line, does not show the change until <kbd>Ctrl</kbd>+<kbd>l</kbd> is
> pressed. It also puts the cursor onto the first char of the next line
> (probably related to #10).

Please try the following patch:

diff --git a/vi.c b/vi.c
index c2ec69b..de99bec 100644
--- a/vi.c
+++ b/vi.c
@@ -1056,6 +1056,7 @@ static void vi(void)
 		int noff = ren_noeol(lbuf_get(xb, xrow), xoff);
 		int otop = xtop;
 		int oleft = xleft;
+		int orow = xrow;
 		int mv, n;
 		term_cmd(&n);
 		vi_arg2 = 0;
@@ -1326,7 +1327,7 @@ static void vi(void)
 			xleft = xcol < xcols ? 0 : xcol - xcols / 2;
 		vi_wait();
 		if (mod || xleft != oleft)
-			vi_drawagain(xcol, mod == 2 && xleft == oleft);
+			vi_drawagain(xcol, mod == 2 && xleft == oleft && xrow == orow);
 		else if (xtop != otop)
 			vi_drawupdate(xcol, otop);
 		if (vi_msg[0])

**Comment by aaronNGi** [comment]
Awesome, that fixes redrawing. The cursor still ends up on the next line though. We can talk about that in #10, as I'm not sure if that's deliberate (<kbd>e</kbd> vs <kbd>w</kbd> motion) or not.
