### ISSUE TITLE
The read ex command fails to read from pipes

### ISSUE THREAD

**Issue by aaronNGi** [aligrudi/neatvi#13]
The `read` ex command fails to read from pipes. I tested `r !seq 10` and it does not insert anything into the buffer.

**Comment by aligrudi** [comment]
Aaron G <notifications@github.com> wrote:
> The `read` ex command fails to read from pipes. I tested `r !seq 10`
> and it does not insert anything into the buffer.

I cannot reproduce the problem; It seems to work here.

**Comment by aaronNGi** [comment]
Doh, turns out I wasn't actually using a space between "r", "!". Sorry, closing this.
