### ISSUE TITLE
Segmentation Fault (vi_prompt)

### ISSUE THREAD

**Issue by FAETHER** [aligrudi/neatvi#17]
If you enter vi_prompt() via pressing ':' and press ^t (or ctrl+t) will result in segfault. Might be low priority to fix, but if you ever press that accidentally you might loose unsaved data.

**Comment by aligrudi** [comment]
Ether <notifications@github.com> wrote:
> If you enter vi_prompt() via pressing ':' and press ^t (or ctrl+t)
> will result in segfault. Might be low priority to fix, but if you ever
> press that accidentally you might loose unsaved data.

Is the issue fixed now?

Thanks,
Ali

**Comment by FAETHER** [comment]
Yep, the issue if fixed, thanks.
