### ISSUE TITLE
My customizations.

### ISSUE THREAD

**Issue by kyx0r** [aligrudi/neatvi#20]
If anybody is interested in customizing this editor and adding extra features, I have uploaded my personal version here: https://github.com/kyx0r/nextvi . 
I did quite a few changes that I felt like was lacking, changes listed in top readme file. Also I might add more stuff as times goes on.

**Comment by aligrudi** [comment]
Kyryl <notifications@github.com> wrote:
> If anybody is interested in customizing this editor and adding extra features, I have uploaded my personal version here: https://github.com/kyx0r/klec . 
> I did quite a few changes that I felt like was lacking, changes listed in top readme file. Also I might add more stuff as times goes on.

Very impressive!

I shall add a link in my litcave page.

	Ali

**Comment by lobre** [comment]
Should this issue be closed?

**Comment by lobre** [comment]
@kyx0r, do you think you can close this issue, as there is not much more that can be done? Thanks a lot.

**Comment by kyx0r** [comment]
Hello Loric, I kept the issue open so that its visible for GitHub visitors and they can learn about the alternative.
