### ISSUE TITLE
Japanese support

### ISSUE THREAD

**Issue by kyx0r** [aligrudi/neatvi#21]
Hello @aligrudi, Japanese characters are rendered as placeholders. Does this indicate that only a certain range of UTF-8 is supported, anything that is above 3 bytes except the Arabic symbols. How do I implement a complete UTF support so that characters are not placeholders and their lengths are correctly interpreted by vi?

**Comment by cjwagenius** [comment]
Does your terminal font face have Japanese characters? Can you type them at the command line?

**Comment by kyx0r** [comment]
Hello, for right now what I am trying to do is really simple, It should not really matter if I can type the characters at command line at the moment, and I have the fonts supported by my terminal 100% sure. So for example, if I remove these two lines of code [here](https://github.com/aligrudi/neatvi/blob/master/ren.c#L143-L144) this is the output I get in neatvi.
 <a href="https://ibb.co/PcY0LDj"><img src="https://i.ibb.co/c6vVBY3/2020-12-11-091112-1366x768-scrot.png" alt="2020-12-11-091112-1366x768-scrot" border="0"></a><br />

**Comment by kyx0r** [comment]
But understand this, while the output is rendered correctly by the terminal, vi does not interpret their length correctly, so moving around, deleting characters, etc does not work correctly.

**Comment by aligrudi** [comment]
MIME-Version: 1.0
Content-Type: text/plain; charset=utf-8
Content-Transfer-Encoding: 8bit

Kyryl <notifications@github.com> wrote:
> This should be valid UTF-8. Here it is, use it for testing
> 日本国
> 平仮名
> 標準語

Please try the following patch.

Thanks,
Ali

diff --git a/ren.c b/ren.c
index 3195598..a294c07 100644
--- a/ren.c
+++ b/ren.c
@@ -154,7 +154,7 @@ int ren_cwid(char *s, int pos)
 	for (i = 0; !conf_placeholder(i, &src, &dst, &wid); i++)
 		if (uc_code(src) == uc_code(s))
 			return wid;
-	return 1;
+	return uc_wid(s);
 }
 
 char *ren_translate(char *s, char *ln)
diff --git a/uc.c b/uc.c
index 4172003..55fec26 100644
--- a/uc.c
+++ b/uc.c
@@ -595,7 +595,7 @@ int uc_isbell(char *s)
 	if (c == ' ' || c == '\t' || c == '\n' || (c <= 0x7f && isprint(c)))
 		return 0;
 	c = uc_code(s);
-	return uc_isdw(c) || uc_iszw(c) || find(c, bchars, LEN(bchars));
+	return uc_iszw(c) || find(c, bchars, LEN(bchars));
 }
 
 /* nonprintable characters */

**Comment by kyx0r** [comment]
Thank you. The patch does exactly what I expect. Are there any false positives to this, otherwise I don't see any reason to not patch this in into the base version of neatvi.

**Comment by aligrudi** [comment]
Kyryl <notifications@github.com> wrote:
> Thank you. The patch does exactly what I expect. Are there any false
> positives to this, otherwise I don't see any reason to not patch this
> in into the base version of neatvi.

Thanks for testing.  Applied.

	Ali
