### ISSUE TITLE
Implement REG_NEWLINE

### ISSUE THREAD

**Issue by kyx0r** [aligrudi/neatvi#22]
Hello, this issue might also apply for neatlibc but REG_NEWLINE is not implemented in regex.c. Are there any plans in doing so? It would be nice to have syntax highlighting for C multi-line comments for example.

**Comment by kyx0r** [comment]
I think the expression in conf.h is actually correct.

**Comment by kyx0r** [comment]
After some investigation, I think multi-line regex might not be possible to do because vi fundamentally is designed such that everything happens line by line instead of just dumping the whole buffer into regex. That said, regex being as robust as it is, it's not turing complete to solve every problem I have.  Just writing C code that does exactly what I want seems to be way easier solution after-all.

**Comment by kyx0r** [comment]
@aligrudi I also tried to make multi-line comment work using regex like this:
```
        {"c", {9 | SYN_IT}, "abc", 0}, // that should terminate the 2st regex and set regex 0
        {"c", {8 | SYN_IT}, ".*", 1}, // match everything that comes
        {"c", {4 | SYN_IT}, "/\\*([^*])*.",  2}, // activate 2nd regex
```
but that does not work, first because the "c" filetype will trigger 2nd regex on everything regardless. It can be fixed somehow. But the biggest issue is that the "end" parameter does not actually end the regex, it only merges the next regex. 

Overall I think this might have been possible if the "end" parameter in structure behaved differently.

**Comment by aligrudi** [comment]
Hello,

Kyryl <notifications@github.com> wrote:
> Hello, this issue might also apply for neatlibc but REG_NEWLINE is
> not implemented in regex.c. Are there any plans in doing so? It would
> be nice to have syntax highlighting for C multi-line comments for
> example.

The problem is that Neatvi highlights lines separately (for
the sake of simplicity and efficiency).   See the invocation
of syn_highlight in led_render() of led.c.  I am not sure how
much work is necessary to change that.

	Ali

**Comment by aligrudi** [comment]
Kyryl <notifications@github.com> wrote:
> After some investigation, I think multi-line regex might not be
> possible to do because vi fundamentally is designed such that
> everything happens line by line instead of just dumping the whole
> buffer into regex. That said, regex being as robust as it is, it's not
> turing complete to solve every problem I have.  Just writing C code
> that does exactly what I want seems to be way easier solution
> after-all.

Maybe a new multi-line highlighting pattern can solve the problem.
Each such pattern can have a starting regex and an ending regex.
What is your opinion?

	Ali

**Comment by aligrudi** [comment]
Kyryl <notifications@github.com> wrote:
> @aligrudi I also tried to make multi-line comment work using regex like this:
> ```
>         {"c", {9 | SYN_IT}, "abc", 0}, // that should terminate the 2st regex and set regex 0
>         {"c", {8 | SYN_IT}, ".*", 1}, // match everything that comes
>         {"c", {4 | SYN_IT}, "/\\*([^*])*.",  2}, // activate 2nd regex
> ```
> but that does not work, first because the "c" filetype will trigger
> 2nd regex on everything regardless. It can be fixed somehow. But the
> biggest issue is that the "end" parameter does not actually end the
> regex, it only merges the next regex.

Currently end indicates at the end of which regular expression group
highlighting should continue.

  "abc(def(ghi)jkl)mno"

Here, for example, if end is 1, highlighting continues from "mno" and
if end is 2, highlighting continues from "jklmno".  By default its
value is 0, meaning the end of group 0 (the whole matched string).

> Overall I think this might have been possible if the "end" parameter
> in structure behaved differently.

It is probably necessary to have two regular expressions for such
patterns: one that shows where the pattern starts and one showing
where it ends.  However, I expect some complexities, for instance,
when the start pattern is not visible in the current page.

	Ali

**Comment by kyx0r** [comment]
> Maybe a new multi-line highlighting pattern can solve the problem. Each such pattern can have a starting regex and an ending regex. What is your opinion? Ali

@aligrudi That's what I've been trying to do also, I managed to make a special regex character like ';' and detect it in some functions inside regex.c set some kind of global variable to ignore every other regex except the starting one. The problem is though that with existing code it would not be able to detect anything else except the starting /* afterwards. And I need the regmatch_t structure to be filled with correct offsets. So even if I use regex to detect the initial "/* I also need a different regex to detect everything else that goes in a block, and then I will have another regex to end "*/" and reset the global variable. The reason I thought about global is so that this feature can be universal and trigger multiline on anything.

**Comment by kyx0r** [comment]
What makes it more complex to understand is that each regex string gets computed into a giant buffer where they are separated by ( and | characters and I can't just find what I want, ie I struggle to come up with a straight forward solution to this problem, because of the limitation of the data structure and overall the way the rset system is designed.

**Comment by aligrudi** [comment]
Kyryl <notifications@github.com> wrote:
> What makes it more complex to understand is that each regex string
> gets computed into a giant buffer where they are separated by ( and |
> characters and I can't just find what I want, ie I struggle to come up
> with a straight forward solution to this problem, because of the
> limitation of the data structure and overall the way the rset system
> is designed.

rset struct is a collection of regular expressions.  The
number returned by rset_find() indicates the index of the
regular expression found at an offset.  I cannot recall now
the main reason for combining regular expressions instead of
compiling many small regular expressions.  However, the
implementation of rset struct can be changed not to combine
the patterns if it helps.

Something like this may work:

	/* syntax highlighting patterns */
	static struct highlight {
		char *ft;		/* the filetype of this pattern */
		int att[16];		/* attributes of the matched groups */
		char *pat;		/* regular expression */
		int end;		/* the group ending this pattern */
		char *endpat;		/* the ending regex for multi-line patterns */
	} highlights[] = {
		...
		{"c", {2 | SYN_IT}, "/\\*", 0, "\\*/"},
		...
	};
	
Maybe for such patterns, endpat need not be regular expressions
at all.  In syn_highlight(), if endpat (conf_highlight() should
be augmented for this additional field) is not NULL, no more
patterns are matched until endpat is found.

	Ali

**Comment by kyx0r** [comment]
Hello @aligrudi and thank you for suggestions. I was able to implement a multi line highlight in my fork. [Link.](https://github.com/kyx0r/neatvi/commit/7bad39ac7b83f9637c5beab1ab494a2d0c0b29c3) This is pretty rough around the edges because as you mentioned if the delimiter is not found or it gets out of view then highlight will not work. But it makes sense overall for it to work like that. I would need to redesign entire highlight system if I wanted to make this work without this limitation. Going to run test run my recent changes in couple of days to make sure that i did oversee everything I can in the code.

**Comment by kyx0r** [comment]
Also right now it probably would not work if I had put more than different 2 multiline patterns on one screen

**Comment by kyx0r** [comment]
But it seems like more than enough for my needs, so I would mark this issue as solved.
