### ISSUE TITLE
Wasting a row for prompt

### ISSUE THREAD

**Issue by kyx0r** [aligrudi/neatvi#23]
Hello @aligrudi, and sorry for spamming your mailbox so much as of late, but vi intentionally does not render the last row where the vi_prompt goes. What was the original design decision for doing so? The way I see it, it's better to render that row also, but erase it whenever the prompt or message has to be displayed. That way you maximize the amount of useful info on the screen. Also if you know where I can change the way it works, I would be very grateful, and save some of my time. 

Also, is github okay method of communication for you, or it's more preferred to send you an email with questions like this? I just do this on github so that anybody else can see if they have similar problems. But I don't think there is a mailing list for your software projects, right?

**Comment by aligrudi** [comment]
Hello Kyryl,

Kyryl <notifications@github.com> wrote:
> Hello @aligrudi, and sorry for spamming your mailbox so much as of
> late, but vi intentionally does not render the last row where the
> vi_prompt goes. What was the original design decision for doing so?
> The way I see it, it's better to render that row also, but erase it
> whenever the prompt or message has to be displayed. That way you
> maximize the amount of useful info on the screen. Also if you know
> where I can change the way it works, I would be very grateful, and
> save some of my time.

The xrows macro (vi.h) specifies the height of the screen; you can
increase its value to term_rows().  Also note that after each screen
update, the message line is redrawn. See vi_drawmsg() calls; you may
need to comment some of these lines.

> Also, is github okay method of communication for you, or it's more
> preferred to send you an email with questions like this? I just do
> this on github so that anybody else can see if they have similar
> problems. But I don't think there is a mailing list for your software
> projects, right?

Both of them are OK; do whichever you prefer (actually I do prefer
emails but Github issues are sent as emails too and I answer them by
replying; it also has the advantage you mentioned).

	Ali

**Comment by kyx0r** [comment]
@aligrudi Thanks! That was very useful, because I knew that xrows did control how it displayed, but I could not find where it was defined, I did not expect it to be a header macro actually. I thought it was just an int somewhere. And yeah putting +1 everywhere is not really sound great, because that variable is used in numerous places. But luckily it was easy to change. I also had to change the way vi_drawmsg() works and some other functions that deal with prompt. And that was easy enough and right now it works perfectly!

**Comment by aligrudi** [comment]
Kyryl <notifications@github.com> wrote:
> @aligrudi Thanks! That was very useful, because I knew that xrows
> did control how it displayed, but I could not find where it was
> defined, I did not expect it to be a header macro actually. I thought
> it was just an int somewhere. And yeah putting +1 everywhere is not
> really sound great, because that variable is used in numerous places.
> But luckily it was easy to change. I also had to change the way
> vi_drawmsg() works and some other functions that deal with prompt. And
> that was easy enough and right now it works perfectly!

Great.

	Ali
