### ISSUE TITLE
@ key

### ISSUE THREAD

**Issue by kyx0r** [aligrudi/neatvi#27]
Hello @aligrudi . Could you explain how you use the @ key? In my fork I have updated the readme:

@ in normal mode: will execute the sequence of normal commands placed in
yank buffer. Specify yank buffer character or hit @ again for 0.

This is from what I understood by reading the source. But it feels like it's hard to imagine a proper use case. I think it's
kinda trying to be what vim macro recording is, but is lacking proper implementation.

**Comment by aligrudi** [comment]
Kyryl <notifications@github.com> wrote:
> Hello @aligrudi . Could you explain how you use the @ key? In my
> fork I have updated the readme:
> 
> @ in normal mode: will execute the sequence of normal commands placed in
> yank buffer. Specify yank buffer character or hit @ again for 0.
> 
> This is from what I understood by reading the source. But it feels
> like it's hard to imagine a proper use case. I think it's
> kinda trying to be what vim macro recording is, but is lacking
> proper implementation.

@@ repeats executing the buffer specified in the previous @.
Maybe the following patch fixes the issue you mentioned:

diff --git a/vi.c b/vi.c
index c9d56a1..c9bde77 100644
--- a/vi.c
+++ b/vi.c
@@ -1026,17 +1026,18 @@ static void vc_repeat(void)
 
 static void vc_execute(void)
 {
-	static int exec_buf;
+	static int exec_buf = -1;
 	int lnmode;
 	int c = vi_read();
-	char *buf;
+	char *buf = NULL;
 	int i;
 	if (TK_INT(c))
 		return;
 	if (c == '@')
 		c = exec_buf;
 	exec_buf = c;
-	buf = reg_get(exec_buf, &lnmode);
+	if (exec_buf >= 0)
+		buf = reg_get(exec_buf, &lnmode);
 	if (buf)
 		for (i = 0; i < MAX(1, vi_arg1); i++)
 			term_push(buf, strlen(buf));

	Ali

**Comment by aligrudi** [comment]
Hello @kyryl,

Kyryl <notifications@github.com> wrote:
> This is from what I understood by reading the source. But it feels like it's hard to imagine a proper use case. I think it's
> kinda trying to be what vim macro recording is, but is lacking proper implementation. 

By the way, @ command is part of POSIX vi.

	Ali
