### ISSUE TITLE
deletion of newline with dw

### ISSUE THREAD

**Issue by kyx0r** [aligrudi/neatvi#28]
Hello @aligrudi when using dw to delete a word if the word is touching the \n the \n is deleted also. Is that a bug or a feature? I know that busybox vi does not delete the \n

**Comment by kyx0r** [comment]
One thing to note that this can be worked around if you use de or dE in this situation, or ce or C and it will not wrap into next line

**Comment by aligrudi** [comment]
Kyryl <notifications@github.com> wrote:
> One thing to note that this can be worked around if you use de or dE
> in this situation, or ce or C and it will not wrap into next line

The behaviour of dw seems implementation dependent.  In Vim, dw does
not remove the words on the next line, unless a count of at least 2
is specified.  Elvis has almost the same behaviour, except that dw
does not remove words on the next line, even if a count is provided.

In Neatvi (see lbuf_wordbeg() in mot.c), dw stops when removing a
blank line (two consecutive new line characters).  Actually, dw
always deletes until the destination of w command, and unlike some
other implementations does not consider special-cases for dw.  I am
not sure, but it seems more consistent.

	Ali

**Comment by kyx0r** [comment]
Yes, I think this is actually fine to stay like that, it was just weird to me that it worked this way. But I just have to adjust my editing skills to use different key combo in those situations.
