### ISSUE TITLE
Help with negated char in posix regex

### ISSUE THREAD

**Issue by kyx0r** [aligrudi/neatvi#31]
Hello Ali, is it possible to somehow get the functionality of a negated char set but for more than 1 character? 

For example see my current expression here I am trying to solve: 
https://github.com/kyx0r/neatvi/blob/master/conf.c#L58

What it does is look for ```*/``` in the string and colors everything that goes backward from the ```*/``` until it finds the closing ```/``` or it doesn't
find it. This is used for C multiline comment implementation and generally it works fine in %90 of the cases. But my problem is that I only match one character as delimiter which is ```/``` but to be a 100% accuracy it needs to match ```/*``` which is 2 characters. But the problem with posix regex is that it does not support look behind and look ahead, but the negated char can only be 1 character.

Is there any way to construct a regex in such a way that it does what I need & is properly delimited?

**Comment by kyx0r** [comment]
I've been pondering this for a while now, I know that it can look at more than 1 character, with a negated set like this:

```"[^c]ar" => The car parked in the garage.```
par and gar will get matched

this is kind of what I need but I need to make it work such that 

```/*``` delimits, matches everythings until ```*/``` and does'nt match anything outside of it

but the trickly part is that it has to only rely on ```*/``` to initialize, so it has to work even if the ```/*``` delimiter is not there

**Comment by aligrudi** [comment]
Hi Kyryl,

Kyryl <notifications@github.com> wrote:
> I've been pondering this for a while now, I know that it can look at
> more than 1 character, with a negated set like this:
> 
> ```"[^c]ar" => The car parked in the garage.```
> par and gar will get matched
> 
> this is kind of what I need but I need to make it work such that 
> 
> ```/*``` delimits, matches everythings until ```*/``` and does'nt
> match anything outside of it
> 
> but the trickly part is that it has to only rely on ```*/``` to
> initialize, so it has to work even if the ```/*``` delimiter is not
> there

The pattern "/\\*([^*]|\\*+[^*/])*\\*+/", which is used in conf.h
for comments in a single line is correct as far as I could verify.
It may be possible to use its second half:

  ([^*]|\\*+[^*/])*\\*+/

There are cases in which the simpler regular expression "([^*]|*[^/])*\\*/"
does not work, but it shows the basic idea: a star can appear in the comment,
only if it is not followed by a slash.

	Ali

**Comment by kyx0r** [comment]
Unfortunately that does not work :(

Here is what both of those expressions produce:

<img src="https://imgpile.com/images/7oynva.png" alt="7oynva.png" border="0" />

This shows the problem I am trying to solve:

<img src="https://imgpile.com/images/7oyush.png" alt="7oyush.png" border="0" />

**Comment by kyx0r** [comment]
If I am able to solve on how to get the botom regex right such that it meets those requirements, I can get rid of the single line regex "/\\*([^*]|\\*+[^*/])*\\*+/" completely and readjust the algorithm to work both ways

**Comment by kyx0r** [comment]
I managed to solve this problem by modifying the regex engine.
Nothing to fancy, just does exactly what I need now.
changes here for the curious:
https://github.com/kyx0r/neatvi/commit/6142c5443891023c713ed83a1ecc3259e7732455

At last it's good that inhouse regex parser is being used instead of C library, as I can customize it to my needs.
