### ISSUE TITLE
clang warnings

### ISSUE THREAD

**Issue by polluks** [aligrudi/neatvi#33]
````
clang -c -Wall -O2 vi.c
vi.c:154:25: warning: comparison of constant -1 with expression of type 'char' is always true
      [-Wtautological-constant-out-of-range-compare]                                              
        while ((c = getchar()) != EOF && c != '\n')
               ~~~~~~~~~~~~~~~ ^  ~~~
vi.c:156:8: warning: comparison of constant -1 with expression of type 'char' is always false     
      [-Wtautological-constant-out-of-range-compare]                                              
        if (c == EOF) {
            ~ ^  ~~~
2 warnings generated.
````

**Comment by aligrudi** [comment]
Stefan ***@***.***> wrote:
> ````
> clang -c -Wall -O2 vi.c
> vi.c:154:25: warning: comparison of constant -1 with expression of type 'char' is always true
>       [-Wtautological-constant-out-of-range-compare]                                              
>         while ((c = getchar()) != EOF && c != '\n')
>                ~~~~~~~~~~~~~~~ ^  ~~~
> vi.c:156:8: warning: comparison of constant -1 with expression of type 'char' is always false     
>       [-Wtautological-constant-out-of-range-compare]                                              
>         if (c == EOF) {
>             ~ ^  ~~~
> 2 warnings generated.
> ````

Thanks.  Should be fixed now.

	Ali

**Comment by polluks** [comment]
thx
