### ISSUE TITLE
^y ^e keys cursor pos mismatch

### ISSUE THREAD

**Issue by kyx0r** [aligrudi/neatvi#35]
@aligrudi xcol is not updated because mod is set to 0, but xoff is being changed.

The following commit in my fork fixes the bug. 
https://github.com/kyx0r/neatvi/commit/a40817079837c6aef2d687785515f38fc723fcfe

Also take a note that the function vi_scrollforeward() has a typo, (should be vi_scrollforward) I addressed that in future commits.

**Comment by aligrudi** [comment]
Kyryl ***@***.***> wrote:
> @aligrudi xcol is not updated because mod is set to 0, but xoff is being changed.
> 
> The following commit in my fork fixes the bug. 
> https://github.com/kyx0r/neatvi/commit/a40817079837c6aef2d687785515f38fc723fcfe
> 
> Also take a note that the function vi_scrollforeward() has a typo, (should be vi_scrollforward) I addressed that in future commits.

Thank you very much.  I will apply them both.

	Ali

**Comment by kyx0r** [comment]
@aligrudi There can be technically 2 solutions to this, either 1: update xcol, 2: update xoff. In my solution I update xoff based on xcol, that basically makes visual cursor pos have correct offset. If you update xcol instead, it will be equivalent to lbuf_indents() position. I think updating xoff is right solution here because cursor should be on the same visual pos as the previous line.

Regards,
Kyryl

**Comment by aligrudi** [comment]
Kyryl ***@***.***> wrote:
> @aligrudi There can be technically 2 solutions to this, either 1:
> update xcol, 2: update xoff. In my solution I update xoff based on
> xcol, that basically makes visual cursor pos have correct offset. If
> you update xcol instead, it will be equivalent to lbuf_indents()
> position. I think updating xoff is right solution here because cursor
> should be on the same visual pos as the previous line.

I cannot reproduce the problem.

In vi.c xoff is updated just after checking whether the cursor
has moved out of the screen.

	Ali

**Comment by kyx0r** [comment]
@aligrudi It's easy to reproduce, you just have to place the cursor onto a longer string than the next string above it, test using ^y
you can clearly see on this screenshot that the output of ga does not match where the cursor is.

see it here: https://0x0.st/-vSO.png

**Comment by aligrudi** [comment]
Kyryl ***@***.***> wrote:
> @aligrudi It's easy to reproduce, you just have to place the cursor onto a longer string than the next string above it, test using ^y
> you can clearly see on this screenshot that the output of ga does not match where the cursor is.

Thanks.  I guess with the following patch the unnecessary redraw
is not necessary.  What is your opinion?  Can it be cleaner?

diff --git a/vi.c b/vi.c
index 48f4e08..839f43a 100644
--- a/vi.c
+++ b/vi.c
@@ -1109,10 +1109,14 @@ static void vi(void)
 			case TK_CTL('e'):
 				if (vi_scrollforward(MAX(1, vi_arg1)))
 					break;
+				noff = vi_col2off(xb, xrow, xcol);
+				xoff = ren_noeol(lbuf_get(xb, xrow), noff);
 				break;
 			case TK_CTL('y'):
 				if (vi_scrollbackward(MAX(1, vi_arg1)))
 					break;
+				noff = vi_col2off(xb, xrow, xcol);
+				xoff = ren_noeol(lbuf_get(xb, xrow), noff);
 				break;
 			case TK_CTL('u'):
 				if (xrow == 0)

**Comment by aligrudi** [comment]
We do not need ren_noeol() call as we call it later in vi().

diff --git a/vi.c b/vi.c
index 48f4e08..039fd10 100644
--- a/vi.c
+++ b/vi.c
@@ -1109,10 +1109,12 @@ static void vi(void)
 			case TK_CTL('e'):
 				if (vi_scrollforward(MAX(1, vi_arg1)))
 					break;
+				xoff = vi_col2off(xb, xrow, xcol);
 				break;
 			case TK_CTL('y'):
 				if (vi_scrollbackward(MAX(1, vi_arg1)))
 					break;
+				xoff = vi_col2off(xb, xrow, xcol);
 				break;
 			case TK_CTL('u'):
 				if (xrow == 0)

**Comment by kyx0r** [comment]
Yep, that's what I did in my fork, also the if statement on vi_scroll* is redundant because it calls MAX and MIN so it can never go out of bounds. I'll clean up all rest of those if statements later in my fork. And having if statement that will never be true in 99% of the time no worth the hassle.

**Comment by aligrudi** [comment]
Kyryl wrote:
> Yep, that's what I did in my fork, also the if statement on
> vi_scroll* is redundant because it calls MAX and MIN so it can never
> go out of bounds. I'll clean up all rest of those if statements later
> in my fork. And having if statement that will never be true in 99% of
> the time no worth the hassle.

Applied.

If the if statement is removed, the position of cursor changes
with ^b at the beginning of file.

	Ali

**Comment by kyx0r** [comment]
> Applied. If the if statement is removed, the position of cursor changes with ^b at the beginning of file. Ali

Right, but that seems too far from a realistic use case scenario.  The user would need to make a conscious decision to move the cursor from the indent position and then try to go up using ^b.  In this scenario doing nothing or changing cursor pos, is equivalent to doing nothing, because the operation itself is undefined behavior pedantically speaking. And different vi implementations do different things in those cases.
