### ISSUE TITLE
neatvi & less

### ISSUE THREAD

**Issue by polluks** [aligrudi/neatvi#47]
FYI neatvi does not support less's v command because of the missing plus option.
You have to define LESSEDIT="%E %g" as a workaround.

**Comment by aligrudi** [comment]
Hi,

Stefan ***@***.***> wrote:
> FYI neatvi does not support less's v command because of the missing plus option.
> You have to define LESSEDIT="%E %g" as a workaround.

Thank you very much.

	Ali
