### ISSUE TITLE
Pasting into macOS terminal

### ISSUE THREAD

**Issue by polluks** [aligrudi/neatvi#48]
upper window = neatvi
lower window = vim
<img width="650" alt="neatvi vs vim" src="https://user-images.githubusercontent.com/4707573/153513734-83e1529d-bc7a-4283-b46e-ac996a27850b.png">

**Comment by aligrudi** [comment]
Hi,

Stefan ***@***.***> wrote:
> upper window = neatvi
> lower window = vim
> <img width="650" alt="neatvi vs vim" src="https://user-images.githubusercontent.com/4707573/153513734-83e1529d-bc7a-4283-b46e-ac996a27850b.png">

You probably need to unset auto-identation:

  :set noai

	Ali

**Comment by polluks** [comment]
Indeed, thanks!
