### ISSUE TITLE
automatic syntax detection via shebang

### ISSUE THREAD

**Issue by apprehensions** [aligrudi/neatvi#57]
languages such as shell or python or sh most likely always have a `#!/bin/sh` or similar at the first line of the file, used by the kernel to execute.

**Comment by kyx0r** [comment]
Nextvi has it as an opt patch:
https://github.com/kyx0r/nextvi/blob/patches/filetype_shebang.patch

**Comment by apprehensions** [comment]
Why not have it consider `conf.h` and submit a PR?

**Comment by aligrudi** [comment]
apprehensions ***@***.***> wrote:
> Why not have it consider `conf.h` and submit a PR?

One goal of Neatvi is to remain minimal, and therefore I have resisted
similar features that do not seem absolutely necessary.  Kyryl's
Nextvi on the other hand is feature-rich; it has many other
interesting features.

	Ali

**Comment by apprehensions** [comment]
I wanted to try out nextvi, but its missing commits of neatvi

**Comment by kyx0r** [comment]
Keep in mind that I do maintain the software. I track whatever changes occur on Neatvi and update Nextvi on as it becomes apparent/necessary.

**Comment by lobre** [comment]
If this is out of scope for neatvi, should the issue be closed?

**Comment by apprehensions** [comment]
according to the author, syntax detection is not necessary for minimalism, so yeah.
