### ISSUE TITLE
Vim support

### ISSUE THREAD

**Issue by faridcher** [aligrudi/neatvi#6]
Salam (Hi),

thanks for neatvi. Is it possible to add the main feature of neatvi, i.e. BiDi support, to Vim? Vim's present support for Persian language is limited and flawed. Neatvi is light and neat, however, my Vim is beefed up with a few packages that neatvi (or vi) doesn't support them. Furthermore, I could not find any licensing information for neatvi in this repo; this might be important if one decides to use neatvi code elsewhere.

thanks

**Comment by aligrudi** [comment]
The internals of Vim is very different from that of Neatvi
and I do not think you can reuse any part of Neatvi for
rendering text in Vim.

About handling Farsi letters properly, I wrote a patch
some years ago:
http://vim.1045645.n5.nabble.com/merge-farsi-handling-into-arabic-c-td1210173i20.html

Also the following may be helpful for Vim:
http://vim.1045645.n5.nabble.com/Typing-Persian-Farsi-in-Vim-td1168936.html

**Comment by faridcher** [comment]
Your discussion in the first shared link seems to be the solution. Although, at the end of the discussion you mentioned that you will release a final patch after more testing. Is that patch ready now? I also have cross- referenced the similar issue on Vim's repo. 

thanks
Farid

**Comment by aligrudi** [comment]
Farid Cheraghi <notifications@github.com> wrote:
> Your discussion in the first shared link seems to be the solution.
> Although, at the end of the discussion you mentioned that you will
> release a final patch after more testing. Is that patch ready now? I
> also have cross- referenced the similar issue on Vim's repo.

Since I do not use Vim for editing in Farsi, my patch
may be out of date.  I think Ameretat Reith can provide
a version that works on recent version of Vim.

	Ali

**Comment by faridcher** [comment]
@reith any idea on this?

**Comment by reith** [comment]
On Mon, Apr 1, 2019 at 10:37 PM Farid Cheraghi <notifications@github.com> wrote:
>
> @reith any idea on this?
>
It's merged into vim:
https://github.com/vim/vim/commit/dc4fa190e7b9d6ba49416ce875d2192c4444d3eb

**Comment by faridcher** [comment]
I have installed the latest dev version of Vim. As I stated earlier there are still a few glitches. The only problem that is solved is the keymapping of Persian chars like ی and ک.

- Unlike neatvi, when English and Persian text are intermixed, the re-ordering algorithm that is present in neatvi is not applied to the characters and thus the text is jumbled.

![image](https://user-images.githubusercontent.com/9982519/55673562-c7c33380-58be-11e9-8ec1-e0775c767cf2.png)

- Unlike neatvi, the RTL or LTR is not context sensitive: In neatvi, when you start a line with  Persian chars, it automatically renders RTL. Conversely, when you begin a line with a English char it renders Left-to-Right. In Vim with arabic support, either RTL or LTR is local to buffer and not to a line.

- Some characters like zero-width separator are not mapped correctly!

thanks

**Comment by aligrudi** [comment]
Farid Cheraghi <notifications@github.com> wrote:
> I have installed the latest dev version of Vim. As I stated earlier there are still a few glitches. The only problem that is solved is the keymapping of Persian chars like ی and ک.

I suggest sending a patch to Bram to fix this.

> - Unlike neatvi, when English and Persian text are intermixed, the
> re-ordering algorithm that is present in neatvi is not applied to the
> characters and thus the text is jumbled.

Doing this in Vim may not be easy.

> - Unlike neatvi, the RTL or LTR is not context sensitive: In neatvi,
> when you start a line with Persian chars, it automatically renders
> RTL. Conversely, when you begin a line with a English char it renders
> Left-to-Right. In Vim with arabic support, either RTL or LTR is local
> to buffer and not to a line.

By the way, in Neatvi the direction of a line is decided based on the
value of td (textdirection) variable and regular expressions specified
in dircontexts[] in conf.h.

> - Some characters like zero-width separator are not mapped correctly!

This should be easy to fix in Vim; I remember using a patch for this too.

	Ali

**Comment by reith** [comment]
On Sun, Apr 7, 2019 at 11:53 AM Ali Gholami Rudi <notifications@github.com>
wrote:

By the way, in Neatvi the direction of a line is decided based on the
> value of td (textdirection) variable and regular expressions specified
> in dircontexts[] in conf.h.
>

Does it work with Hebrew for instance? I used to naively traverse over
character codes scraped from Unicode dataset:
https://github.com/reith/hemianopsia/blob/master/core.js
I said naive because that list isn't bucketized, but I think it's probably
still faster than regex, and maybe more reliable?

**Comment by aligrudi** [comment]
reith <notifications@github.com> wrote:
> By the way, in Neatvi the direction of a line is decided based on the
> > value of td (textdirection) variable and regular expressions specified
> > in dircontexts[] in conf.h.
> >
> 
> Does it work with Hebrew for instance? I used to naively traverse over
> character codes scraped from Unicode dataset:
> https://github.com/reith/hemianopsia/blob/master/core.js

It probably works; add Hebrew right-to-left characters to
CR2L macro in conf.h.  You can also add a Hebrew keymap to
kmap.h.

> I said naive because that list isn't bucketized, but I think it's probably
> still faster than regex, and maybe more reliable?

Regular expression are slower but probably more flexible for
specifying custom text direction rules (dircontexts[] and
dirmarks[] in conf.h).

	Ali

**Comment by reith** [comment]
On Sun, Apr 7, 2019 at 12:39 PM Ali Gholami Rudi
<notifications@github.com> wrote:
>
> reith <notifications@github.com> wrote:
> > By the way, in Neatvi the direction of a line is decided based on the
> > > value of td (textdirection) variable and regular expressions specified
> > > in dircontexts[] in conf.h.
> > >
> >
> > Does it work with Hebrew for instance? I used to naively traverse over
> > character codes scraped from Unicode dataset:
> > https://github.com/reith/hemianopsia/blob/master/core.js
>
> It probably works; add Hebrew right-to-left characters to
> CR2L macro in conf.h. You can also add a Hebrew keymap to
> kmap.h.
My point was it doesn't need defining another keymap, but I don't know
whether keymap used elsewhere or not.

**Comment by aligrudi** [comment]
reith <notifications@github.com> wrote:
> > It probably works; add Hebrew right-to-left characters to
> > CR2L macro in conf.h. You can also add a Hebrew keymap to
> > kmap.h.
> My point was it doesn't need defining another keymap, but I don't know
> whether keymap used elsewhere or not.

Defining a keymap is necessary only if you want to type in Hebrew
in Neatvi without changing the keyboard language of your OS.
Note that after defining an array like kmap_fa[], you need to add it
to the kmaps[] array.

	Ali

**Comment by faridcher** [comment]
What do you mean it is difficult? does it mean it is harder to implement it for Vim as compared to Vi?
why you didn't extend (fork, patch) Vim in the first place!? I think, for now, I will switch back and forth between Vim and Neatvi even though it is sub-optimal; I assume this is what you do as well. I will study the Neatvi code later on. 

thanks

**Comment by aligrudi** [comment]
Farid Cheraghi <notifications@github.com> wrote:
> What do you mean it is difficult? does it mean it is harder to
> implement it for Vim as compared to Vi?

Neatvi was written from scratch, and editing bidirectional
text was one of its main goals.  In Vim, however, this was
not a main concern when it was developed.  This probably
makes supporting bidirectional text in Vim harder.  However,
someone more familiar with the internals of Vim may not find
it very difficult.

> why you didn't extend (fork, patch) Vim in the first place!? I
> think, for now, I will switch back and forth between Vim and Neatvi
> even though it is sub-optimal; I assume this is what you do as well. I
> will study the Neatvi code later on.

Nowadays I rarely use Vim.  I do not use most of the
features available in Vim though.

	Ali
