### ISSUE TITLE
ex: pipe parsing broken

### ISSUE THREAD

**Issue by polluks** [aligrudi/neatvi#63]
:5|10|15 should result in line 15.
https://github.com/kyx0r/nextvi/commit/d200131dd7d36a45ac4083db428a169b9416e7d1

**Comment by aligrudi** [comment]
Stefan ***@***.***> wrote:
> :5|10|15 should result in line 15.
> https://github.com/kyx0r/nextvi/commit/d200131dd7d36a45ac4083db428a169b9416e7d1

Should be fixed now.

	Ali

**Comment by polluks** [comment]
👍
