### ISSUE TITLE
C Multi line comment doesn't get highlighted

### ISSUE THREAD

**Issue by batalooppak** [aligrudi/neatvi#65]
In MacOS
with neatvi latest pull.

In C file:
<img width="367" alt="Screen Shot 2023-10-24 at 01 12 05" src="https://github.com/aligrudi/neatvi/assets/906341/5054a5c4-7b1d-4290-bda5-4961e49b498d">

**Comment by aligrudi** [comment]
Lucas ***@***.***> wrote:
> In MacOS
> with neatvi latest pull.
> 
> In C file:
> <img width="367" alt="Screen Shot 2023-10-24 at 01 12 05" src="https://github.com/aligrudi/neatvi/assets/906341/5054a5c4-7b1d-4290-bda5-4961e49b498d">

Neatvi's syntax highlighting processes individual lines and cannot
highlight multi-line patterns.  Nevertheless, you can add the following
pattern to highlights array in conf.h to highlight kernel-style
C-comments:

	{"c", {2 | SYN_IT}, "^\t*(/\\*.*| \\*.*| \\*\\//)$"},

It highlights comments similar to this:

	/* abc
	 * def
	 */

	Ali

**Comment by aligrudi** [comment]
I updated conf.h to include this pattern.

	Ali

**Comment by lobre** [comment]
I validate that it works. To me, this ticket can be closed.

**Comment by batalooppak** [comment]
I also validate. Thanks!
