### ISSUE TITLE
Add a gitignore for build artifacts

### ISSUE THREAD

**Issue by lobre** [aligrudi/neatvi#66]
Hello,

When building the project with `make`, it leaves a lot of build-related files untracked in git.

This would benefit from having a `.gitignore` to avoid listing them in git.

Would you be accepting a PR for that?

```
$ git status
On branch master
Your branch is up to date with 'origin/master'.

Untracked files:
  (use "git add <file>..." to include in what will be committed)
        cmd.o
        conf.o
        dir.o
        ex.o
        lbuf.o
        led.o
        mot.o
        reg.o
        regex.o
        ren.o
        rset.o
        rstr.o
        sbuf.o
        syn.o
        tag.o
        term.o
        uc.o
        vi
        vi.o
```

Thanks

**Comment by aligrudi** [comment]
Loric Brevet ***@***.***> wrote:
> I created a pull request on Github for this, but if I understand correctly, you are only interacting through emails. So here is the content of my PR here, in case you are interested in adding this `.gitignore`.
> 
> ```
> # libs
> *.o
> *.ko
> *.obj
> *.elf
> 
> # objects
> *.dll
> *.so
> *.so.*
> *.dylib
> 
> # executables
> *.exe
> *.out
> *.hex
> vi
> ```

Thanks.  I usually use a .gitignore file that ignores itself
and do not store it in the repository.  In any case, I shall
commit a shorter version.

	Ali

**Comment by lobre** [comment]
Thank you, I will close this issue as your proposed gitignore is good enough for now.
