### ISSUE TITLE
Support new BiDi standard

### ISSUE THREAD

**Issue by XVilka** [aligrudi/neatvi#8]
There is a BiDi/RTL [standardization effort](https://terminal-wg.pages.freedesktop.org/bidi/). And it is already supported by VTE library (not yet released though), see https://terminal-wg.pages.freedesktop.org/bidi/implementations.html#vte

See also https://gist.github.com/XVilka/a0e49e1c65370ba11c17 for tracking other terminals and programs.

**Comment by faridcher** [comment]
After updating my Gnome Terminal with the new BIDI libvte (thanks to @XVilka ), neatvi does not render BIDI text correctly anymore.

**Comment by aligrudi** [comment]
Farid Cheraghi <notifications@github.com> wrote:
> After updating my Gnome Terminal with the new BIDI libvte (thanks to @XVilka ), neatvi does not render BIDI text correctly anymore.

Sorry for my delay in answering.

The main issue is that I think a terminal should change neither the position
nor the shape of characters on the screen and rendering bidirectional text
should be handled by programs that use the terminal and not the terminal
itself.  A terminal is like a simple shelf on which you put characters;
it should not change their order (or shape) on its own.  Breaking this
assumption by default does not seem a good idea.  This may be a convenient
feature for some users; in that case I suggest not changing the default
behaviour, and adding an option for that instead.

**Comment by faridcher** [comment]
Thanks for the clarification. I really expect BIDI support in the terminal by default because I personally prefer to use Persian letters for certain file names; I am quite happy that I do not have to use `bicon` anymore. I think the best practice is to provide this option at the application level e.g. in the Vim and/or Neatvi. I think the current situation with vim showing BIDI text correctly but not being able to layout the text from "right to left" direction could be easily overcome.  Neatvi could also provide the same runtime option IMHO.

**Comment by aligrudi** [comment]
Farid Cheraghi ***@***.***> wrote:
> Thanks for the clarification. I really expect BIDI support in the
> terminal by default because I personally prefer to use Persian letters
> for certain file names; I am quite happy that I do not have to use
> `bicon` anymore. I think the best practice is to provide this option
> at the application level e.g. in the Vim and/or Neatvi. I think the
> current situation with vim showing BIDI text correctly but not being
> able to layout the text from "right to left" direction could be easily
> overcome.  Neatvi could also provide the same runtime option IMHO.

I have added the LNPREF macro in conf.h that can be used to
disable BiDi in vte-based terminals; the comment of its
previous line gives more details.

Nevertheless, I disapprove the proposal.

Thanks,
Ali

**Comment by faridcher** [comment]
@aligrudi 
Thank you very much for the enhancement. I will test it as soon as possible.

**Comment by lobre** [comment]
If the proposal is disapproved, should this issue be closed?

**Comment by aligrudi** [comment]
Loric Brevet ***@***.***> wrote:
> If the proposal is disapproved, should this issue be closed?

I think so.

In any case, as mentioned, to use Neatvi in terminals that
implement this proposal, NLPREF macro in conf.h can be
defined as "\33[8l".

	Ali

**Comment by lobre** [comment]
I cannot close it myself, so I let @XVilka or yourself @aligrudi close it.

**Comment by aligrudi** [comment]
Loric Brevet ***@***.***> wrote:
> I cannot close it myself, so I let @XVilka or yourself @aligrudi close it.

I rarely use the web interface.  Is there was a way to do
so by replying to an issue (via email).

Thanks,
Ali

**Comment by lobre** [comment]
Hmm. I am not sure issues can be closed by mail.

**Comment by lobre** [comment]
@XVilka, would you be able to close it yourself? Thanks a lot.

**Comment by XVilka** [comment]
> @XVilka, would you be able to close it yourself? Thanks a lot.

Done.
