### ISSUE TITLE
white background when mixing RTL/LTR in a line

### ISSUE THREAD

**Issue by mohammad5305** [aligrudi/neatvi#84]
after mixing persian and english, persian gets white background, its a not terminal issue because both st and lxterminal had this issue, also removed all highlights but still gets white bg

![image](https://github.com/aligrudi/neatvi/assets/71145952/8c7af9c3-5886-4de7-82f4-aeb3d7766df0)

**Comment by aligrudi** [comment]
"mohammad.b" ***@***.***> wrote:
> after mixing persian and english, persian gets white background, its a not terminal issue because both st and lxterminal had this issue, also removed all highlights but still gets white bg
> 
> ![image](https://github.com/aligrudi/neatvi/assets/71145952/8c7af9c3-5886-4de7-82f4-aeb3d7766df0)

That is expected, as the text in the reverse direction of the line
is highlighted using SYN_REVDIR (see conf.h).  You can override
that if you wish.

Also, you can define LNPREF as "\33[3l]" in conf.h to disable BiDi
in vte-based terminals (that is probably why the text is not rendered
properly in your screenshot).

	Ali
