### ISSUE TITLE
Syntax highlighting for POSIX shell

### ISSUE THREAD

**Issue by emmatebibyte** [aligrudi/neatvi#85]
I’ve noticed neatvi has syntax highlighting for some languages, would it be possible to implement it for POSIX shell?

**Comment by aligrudi** [comment]
Emma Tebibyte ***@***.***> wrote:
> I’ve noticed neatvi has syntax highlighting for some languages, would it be possible to implement it for POSIX shell?

Shell scripts are highlighted; by default it is turned on only for
files with sh extension.  For other files, you can execute `:ft sh`
or change file type patterns in conf.h.

	Ali

**Comment by emmatebibyte** [comment]
I see. Thank you
