### ISSUE TITLE
r<CR>

### ISSUE THREAD

**Issue by polluks** [aligrudi/neatvi#86]
I expected a line split... but it behaves as `D` without yanking.

**Comment by aligrudi** [comment]
Stefan ***@***.***> wrote:
> I suspected a line split... but it behaves as `D` without yanking.

Must be fixed now.

Thanks,
Ali

**Comment by polluks** [comment]
Better... what about an extra refresh?

**Comment by aligrudi** [comment]
Stefan ***@***.***> wrote:
> Better... what about an extra refresh?

For commands that usually modify a single line, such as ~, r, D, and
x, only the current line is updated, unless xrow or xleft changes, in
which case the whole screen is updated.  Do you mean the update in
the second case?

	Ali

**Comment by polluks** [comment]
I was thinking of `r<CR>` should be equivalent to `i<CR><ESC>`, therefore the second case.

**Comment by aligrudi** [comment]
Stefan ***@***.***> wrote:
> I was thinking of `r<CR>` should be equivalent to `i<CR><ESC>`, therefore the second case.

OK.

Sorry, I am not sure if I understand the second problem.
Do you mean that neatvi must redraw the screen but it
does not, or that neatvi redraws the screen unnecessarily?

	Ali

**Comment by kyx0r** [comment]
Hello Ali,

I think the confusion is that in your version mod = 2 redraws more than 1 line. This op has to redraw 2 lines, original
and the new line. That would imply comment about mod = 2 is wrong.

Kind Regards,
Kyryl

**Comment by aligrudi** [comment]
Hello Kyryl.

Kyryl ***@***.***> wrote:
> I think the confusion is that in your version mod = 2 redraws more than 1 line. This op has to redraw 2 lines, original
> and the new line. That would imply comment about mod = 2 is wrong.

Is it OK then?  I was worried that the screen is not updated
in some cases.

	Ali

**Comment by polluks** [comment]
works fine but...
```
[...]
test/e14.sh: Failed
--- /tmp/.neatvi1	2024-06-25 20:25:02
+++ /tmp/.neatvi2	2024-06-25 20:25:02
@@ -1,3 +1,2 @@
-a
 b
 c

**Comment by aligrudi** [comment]
Stefan ***@***.***> wrote:
> works fine but...
> ```
> [...]
> test/e14.sh: Failed
> --- /tmp/.neatvi1	2024-06-25 20:25:02
> +++ /tmp/.neatvi2	2024-06-25 20:25:02
> @@ -1,3 +1,2 @@
> -a
>  b
>  c

Thanks, fixed.

Missed this one after renaming ye command to rs.
Now we have rs and rx.

	Ali
