### ISSUE TITLE
[Request] Filtering ranges through an external command

### ISSUE THREAD

**Issue by aaronNGi** [aligrudi/neatvi#9]
I'm currently window shopping for an editor because my current linux distro does not package `nvi` and building it is quite a pain in the butt. There also seems to be a need to heavily patch it (most linux distros do). I'm not going to touch that myself...

Now, `neatvi` ticks almost all the boxes. What I'm also missing is ex-mode history and file auto-completion but I can live without those.

A bigger issue for me is the lack of the ability to filter ranges through an external command. Being able to do that is a rather crucial feature in my opinion, as it gives a lot of power. Is there some kind of roadmap for this project or a general list of features you want to implement and things you will never do (like split windows for instance)?

**Comment by aligrudi** [comment]
Aaron G <notifications@github.com> wrote:
> A bigger issue for me is the lack of the ability to filter ranges
> through an external command. Being able to do that is a rather crucial
> feature in my opinion, as it gives a lot of power. Is there some kind

Do you mean ! vi-mode command?

> of roadmap for this project or a general list of features you want to
> implement and things you will never do (like split windows for
> instance)?

My goal was to implement the most commonly used features mentioned
in POSIX.  I also sometimes included useful and convenient features
that do not make the code very complicated.

**Comment by aaronNGi** [comment]
> Do you mean ! vi-mode command?

No, I mean the ex command `!`. For example `:.,+20 !sort` or also super useful: `:5,10 !fmt -s -p \#`. So, opposed to `:w !<command>`, it takes a range, pipes the lines from that range to an external command and replaces them with the output of \<command>.

> My goal was to implement the most commonly used features mentioned
in POSIX.  I also sometimes included useful and convenient features
that do not make the code very complicated.

That sounds good.

**Comment by aligrudi** [comment]
Aaron G <notifications@github.com> wrote:
> No, I mean the ex command `!`. For example `:.,+20 !sort` or also
> super useful: `:5,10 !fmt -s -p \#`. So, opposed to `:w !<command>`,
> it takes a range, pipes the lines from that range to an external
> command and replaces them with the output of \<command>.

Please test the following patch:

diff --git a/ex.c b/ex.c
index da48b05..220c106 100644
--- a/ex.c
+++ b/ex.c
@@ -735,13 +735,26 @@ static int ec_substitute(char *ec)
 
 static int ec_exec(char *ec)
 {
+	char loc[EXLEN];
 	char arg[EXLEN];
+	int beg, end;
+	char *text;
+	char *rep;
 	ex_modifiedbuffer(NULL);
+	ex_loc(ec, loc);
 	if (ex_expand(arg, ex_argeol(ec)))
 		return 1;
 	ex_print(NULL);
-	if (cmd_exec(arg))
+	if (!loc[0])
+		return cmd_exec(arg);
+	if (ex_region(loc, &beg, &end))
 		return 1;
+	text = lbuf_cp(xb, beg, end);
+	rep = cmd_pipe(arg, text, 1, 1);
+	if (rep)
+		lbuf_edit(xb, rep, beg, end);
+	free(text);
+	free(rep);
 	return 0;
 }

**Comment by aaronNGi** [comment]
Hey, nice. The function itself works perfectly as far as I can tell. While it makes total sense when running commands normally (`:!<command>`), from a usability standpoint it makes more sense if there was no call to `vi_wait()` when using `:<range>!<command>.

**Comment by aaronNGi** [comment]
I noticed something somewhat related: Since '|' is used as the ex command separator, you can't use pipes in external commands. Most vi-clones seem to ignore '|' as the command separator when the ex command is `!` and always use it as parameter for the external command. That means you can't run `:!echo foo | !echo bar`, but maybe that's better than having to escape the '|'?!

**Comment by aligrudi** [comment]
Aaron G <notifications@github.com> wrote:
> Hey, nice. The function itself works perfectly as far as I can tell.
> While it makes total sense when running commands normally
> (`:!<command>`), from a usability standpoint it makes more sense if
> there was no call to `vi_wait()` when using `:<range>!<command>.

Pushed.

**Comment by aligrudi** [comment]
Aaron G <notifications@github.com> wrote:
> I noticed something somewhat related: Since '|' is used as the ex
> command separator, you can't use pipes in external commands. Most
> vi-clones seem to ignore '|' as the command separator when the ex
> command is `!` and always use it as parameter for the external
> command. That means you can't run `:!echo foo | !echo bar`, but maybe
> that's better than having to escape the '|'?!

OK.  Now | is not a command separator for :! command.

**Comment by aaronNGi** [comment]
> OK.  Now | is not a command separator for :! command.

Thanks, it works perfectly now!

Something I just noticed, which seems to be unrelated to the last 2 commits: the `read` ex command fails to read from pipes. I tested `r !seq 10` and it does not read anything.

I will close this issue and create a new one for it.
